FROM ubuntu:18.04

## install node.js
RUN apt-get update
RUN apt-get install -y nodejs npm

# add our code
COPY . /app
WORKDIR /app

# install ruby gem
RUN apt install -y ruby-dev gcc automake libtool rubygems build-essential
# RUN gem install sass --no-user-install
RUN gem install scss_lint --no-user-install

# install npm deps
RUN npm install
RUN npm run build
RUN npm run ssr-build

EXPOSE 3000
CMD ["npm", "run", "ssr-start"]
