import { makeApiCall } from "../api/request";
import * as notificationApi from "../api/notification";


export const NOTIFICATIONS_FETCH_START = "NOTIFICATIONS/NOTIFICATIONS_FETCH_START";
export const NOTIFICATIONS_FETCH_SUCCESS = "NOTIFICATIONS/NOTIFICATIONS_FETCH_SUCCESS";
export const NOTIFICATIONS_FETCH_ERROR = "NOTIFICATIONS/NOTIFICATIONS_FETCH_ERROR";
export const notificationsFetch = makeApiCall(notificationApi.notificationsFetch, NOTIFICATIONS_FETCH_START, NOTIFICATIONS_FETCH_SUCCESS, NOTIFICATIONS_FETCH_ERROR);

export const NOTIFICATION_MARK_READ_START = "NOTIFICATIONS/NOTIFICATION_MARK_READ_START";
export const NOTIFICATION_MARK_READ_SUCCESS = "NOTIFICATIONS/NOTIFICATION_MARK_READ_SUCCESS";
export const NOTIFICATION_MARK_READ_ERROR = "NOTIFICATIONS/NOTIFICATION_MARK_READ_ERROR";
export const notificationsMarkRead = makeApiCall(notificationApi.notificationsMarkRead, NOTIFICATION_MARK_READ_START, NOTIFICATION_MARK_READ_SUCCESS, NOTIFICATION_MARK_READ_ERROR);
